block.settings.oho_menu_block:*:
  type: block_settings
  label: 'OHO Menu Block'
  mapping:
    nav_type:
      type: string
      label: 'Nav type'
    level:
      type: integer
      label: 'Starting or relative level'
    depth:
      type: integer
      label: 'Maximum number of levels'
    expand:
      type: boolean
      label: 'Expand all menu links'
    sibling_depth:
      type: integer
      label: 'Sibling depth difference'
    title_type:
      type: string
      label: 'Title type'
    title_level:
      type: integer
      label: 'Title level'
    title_show_link:
      type: boolean
      label: 'Show title as a link'
