features:
  node_user_picture: 1
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 0
  path: 'public://favicon_2.ico'
  mimetype: image/vnd.microsoft.icon
oho_base_breadcrumbs_display_home: 0
oho_base_breadcrumbs_display_starting_level: '2'
